### ISSUE TITLE
채팅 API

### ISSUE THREAD

**Issue by yeonjae-do** [Team-Remember/rememberMe-backend#18]
**문제 제기**
- 사용자는 채팅 기능을 사용할 수 있어야한다.

**기능 요약**
- 사용자는 다른 사용자, AI 챗봇과 채팅을 한다.

**기능 설명**
- 사용자는 다른 사용자와 채팅을 할 수 있다.
- 사용자는 복원된 AI 챗봇과 채팅을 할 수 있다.
- 사용자는 본인이 작성한 채팅을 삭제할 수 있다.
- 사용자가 남긴 채팅 로그는 데이터베이스에 저장된다.

**할일 목록**
- 채팅 생성 API
- 채탕 저장 API
- 채팅 삭제 API

**비고**

**Comment by pjhhs021** [comment]
완료
